### ISSUE TITLE
CustomDomainSuffix only in multinode?

### ISSUE THREAD

**Issue by BjornAnd** [mattmcspirit/azurestack#101]
**Describe the issue**
I get the message "You've specified the -customDomainSuffix parameter but not the -multiNode switch. Please rerun the script and provide the -multiNode switch, or remove the -customDomainSuffix if this is an ASDK."
We have been using custom domains since like for ever.. But i don't have a multinode ASDK. :(

**Hardware**
Physical servers, HP an Dell. 2x Intel E5-2660, 256GB RAM, 4x1TB SSD + 10x6TB HDD

**Send the logs**
Do you need the logs for this? 

**Additional context**
I don't have any more context, just don't understand this change.

**Comment by mattmcspirit** [comment]
Leave this with me!

**Comment by BjornAnd** [comment]
I think i have a workaround.

**Comment by mattmcspirit** [comment]
Yeah, just comment out 1113 to 1117:
```powershell
    if (($customDomainSuffix -ne "local.azurestack.external") -and ($multinode -eq $false)) {
        Set-Location $ScriptLocation
        Write-Host "You've specified the -customDomainSuffix parameter but not the -multiNode switch. Please rerun the script and provide the -multiNode switch, or remove the -customDomainSuffix if this is an ASDK." -ForegroundColor Red
        Break
    }
```

Should work fine after that i think!

**Comment by BjornAnd** [comment]
as a side note i also had to edit the C:\AzSPoC\Scripts\addImage.ps1
Line 122 (from "Volume1" to "SU1_Volume")

121   if ($multiNode -eq $false) {
122       $imageRootPath = "C:\ClusterStorage\SU1_Volume"
123    }
124    else {
125        $imageRootPath = $azsPath
126    }

**Comment by mattmcspirit** [comment]
Hmm, is that with 1908? I guess the default CSV volume has changed for the ASDK.  I'll investigate when my next deployment has finished.  Thanks!

**Comment by BjornAnd** [comment]
Sorry. Yes. That's the 1908.

**Comment by mattmcspirit** [comment]
Should now be fixed in the 1908 version.  Thanks!
