### ISSUE TITLE
Unable to complete install using script

### ISSUE THREAD

**Issue by duanecr** [mattmcspirit/azurestack#104]
I have a new install of ASDK that passes all the tests.  It was already registered, and I'm using the commands from "Step 3" usage scenario #3.  Everything works until it is "Testing Azure Stack login with Azure Active Directory".  At that point, it tells me it is logging into the Default Provider Subscription using my azure admin account.  It then returns the following error:

[4:53 PM]::[TEST LOGINS]:: The provided account administrator@tenantname.onmicrosoft.com does not have access to subscription name "Default Provider Subscription". Please try log
ging in with different credentials or a different subscription name..Exception.Message

I do not currently have a subscription with that name.  My subscription name is "MSDN Subscription".

I have verified that the account logging in does have "Owner" permissions to the subscription and is a global administrator for the tenant.  Is there something else that I am missing for this to work?

**Comment by mattmcspirit** [comment]
Hi,

The Default Provider Subscription is a subscription unique to the **Azure Stack** and not Azure. The error you're seeing would indicate that the account doesn't have enough privilege against that subscription.  I'm assuming that this wasn't the account you used t deploy the ASDK itself? If it was, it automatically has owner privilege on the Default Provider Sub.

So, to check and update this, simply log into the Azure Stack Admin portal, go to Subscriptions, find the Default Provider Subscription and ensure that your account is an owner for that subscription, then rerun my script.

Thanks,
Matt

**Comment by duanecr** [comment]
Thank you.  That was my problem.  I had joined using my @hotmail.com account and had not added the @domain.onmicrosoft.com to the AS subscription.

DC
