### ISSUE TITLE
Alternate EnvironmentName

### ISSUE THREAD

**Issue by gless** [mattmcspirit/azurestack#106]
Are there any changes needed to the script if your environment is "AzureUSGovernment"?

We updated the script to use "AzureUSGovernment" instead of AzureCloud or AzureChinaCloud, however, the process never completes and we get the following:

Current number of failed jobs: 7

Name                   StartTime            EndTime              Duratio
----                   ---------            -------              -------
AddUbuntuImage         9/23/2019 3:32:40 PM 9/23/2019 3:32:47 PM 0m:7s
AddServerCore2016Image 9/23/2019 3:32:41 PM 9/23/2019 3:32:47 PM 0m:6s
AddServerFull2016Image 9/23/2019 3:32:42 PM 9/23/2019 3:32:47 PM 0m:5s
AddServerCore2019Image 9/23/2019 3:32:42 PM 9/23/2019 3:32:48 PM 0m:5s
AddServerFull2019Image 9/23/2019 3:32:43 PM 9/23/2019 3:32:48 PM 0m:5s
AddAppServicePreReqs   9/23/2019 3:32:50 PM 9/23/2019 3:32:57 PM 0m:6s
DeployAppService       9/23/2019 3:32:51 PM 9/23/2019 3:34:03 PM 1m:12s

Thanks,
Eric

**Comment by mattmcspirit** [comment]
Hi Eric,

I haven't tested against AzureGov I'm afraid, so i expect there's just some subtlety where it's trying to auth against AzureGov compared with AzureCloud. May be something to do with tokens for the images, but i'm not sure on the AppServicePreReq stage.

Would you be able to send me your logs to asdkconfigurator@outlook.com, and I'll take a look? I only really need the AppServicePreReq, and the UbuntuImage log for now, as i suspect if I fix for those, the rest will sort themselves out.

Thanks!
Matt

**Comment by mattmcspirit** [comment]
Should be fixed in the upcoming 1908.2 release of the script - you'll be able to specify a new flag, -azureEnvironment, and include your chosen environment.  Default will be AzureCloud, if none are specified.
