### ISSUE TITLE
MySQLDBVM Failure

### ISSUE THREAD

**Issue by caaustin74** [mattmcspirit/azurestack#116]
I ended up skipping the MySQL altogether and everything else worked like a champ.

**Describe the issue**
MySQLDBVM            : Failed
MySQLAddHosting      : Failed

>> TerminatingError(New-AzureRmResourceGroupDeployment): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 10:23:58 PM - Resource Microsoft.Compute/virtualMachines/extensions 'mysqlhost/CustomScriptExtension' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'CustomScriptExtension'. Error message: Command returned an error.\n---stdout---\n.deb ...\r\nUnpacking cloud-init (19.3-41-gc4735dd3-0ubuntu1~16.04.1) over (19.2-36-g059d049c-0ubuntu2~16.04.1) ...\r\nProcessing triggers for man-db (2.7.5-1) ...\r\nProcessing triggers for libc-bin (2.23-0ubuntu11) ...\r\nProcessing triggers for ureadahead (0.100.0-19.1) ...\r\nProcessing triggers for systemd (229-4ubuntu21.23) ...\r\nSetting up libdbus-1-3:amd64 (1.10.6-1ubuntu3.5) ...\r\nSetting up dbus (1.10.6-1ubuntu3.5) ...\r\nA reboot is required to replace the running dbus-daemon.\r\nPlease reboot the system when convenient.\r\nSetting up libpam-systemd:amd64 (229-4ubuntu21.23) ...\r\ndebconf: unable to initialize frontend: Dialog\r\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\r\ndebconf: falling back to frontend: Readline\r\nSetting up udev (229-4ubuntu21.23) ...\r\naddgroup: The group `input' already exists as a system group. Exiting.\r\nupdate-initramfs: deferring update (trigger activated)\r\nSetting up libwbclient0:amd64 (2:4.3.11+dfsg-0ubuntu0.16.04.24) ...\r\nSetting up samba-libs:amd64 (2:4.3.11+dfsg-0ubuntu0.16.04.24) ...\r\nSetting up python-samba (2:4.3.11+dfsg-0ubuntu0.16.04.24) ...\r\nSetting up samba-common (2:4.3.11+dfsg-0ubuntu0.16.04.24) ...\r\ndebconf: unable to initialize frontend: Dialog\r\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\r\ndebconf: falling back to frontend: Readline\r\nSetting up samba-common-bin (2:4.3.11+dfsg-0ubuntu0.16.04.24) ...\r\nSetting up libsqlite3-0:amd64 (3.11.0-1ubuntu1.3) ...\r\nSetting up libpcap0.8:amd64 (1.7.4-2ubuntu0.1) ...\r\nSetting up git-man (1:2.7.4-0ubuntu1.7) ...\r\nSetting up git (1:2.7.4-0ubuntu1.7) ...\r\nSetting up linux-cloud-tools-common (4.4.0-170.199) ...\r\nSetting up linux-tools-common (4.4.0-170.199) ...\r\nSetting up sosreport (3.6-1ubuntu0.16.04.4) ...\r\nSetting up unattended-upgrades (1.1ubuntu1.18.04.7~16.04.5) ...\r\ndebconf: unable to initialize frontend: Dialog\r\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\r\ndebconf: falling back to frontend: Readline\r\nSetting up cloud-init (19.3-41-gc4735dd3-0ubuntu1~16.04.1) ...\r\ndebconf: unable to initialize frontend: Dialog\r\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\r\ndebconf: falling back to frontend: Readline\r\nLeaving 'diversion of /etc/init/ureadahead.conf to /etc/init/ureadahead.conf.disabled by cloud-init'\r\nSetting up python3-distupgrade (1:16.04.29) ...\r\nSetting up python3-update-manager (1:16.04.17) ...\r\nSetting up ubuntu-release-upgrader-core (1:16.04.29) ...\r\nSetting up update-manager-core (1:16.04.17) ...\r\nProcessing triggers for libc-bin (2.23-0ubuntu11) ...\r\nProcessing triggers for initramfs-tools (0.122ubuntu8.16) ...\r\nupdate-initramfs: Generating /boot/initrd.img-4.15.0-1063-azure\r\nW: mdadm: /etc/mdadm/mdadm.conf defines no arrays.\r\nCanceled hold on walinuxagent.\nReading package lists...\nBuilding dependency tree...\nReading state information...\nThe following package was automatically installed and is no longer required:\n  grub-pc-bin\nUse 'sudo apt autoremove' to remove it.\nThe following additional packages will be installed:\n  libaio1 libmecab2 mecab-ipadic mecab-ipadic-utf8 mecab-utils mysql-common\n  mysql-community-client mysql-community-client-core mysql-community-server\n  mysql-community-server-core\nThe following NEW packages will be installed:\n  libaio1 libmecab2 mecab-ipadic mecab-ipadic-utf8 mecab-utils mysql-client\n  mysql-common mysql-community-client mysql-community-client-core\n  mysql-community-server mysql-community-server-core mysql-server\n0 upgraded, 12 newly installed, 0 to remove and 5 not upgraded.\nNeed to get 32.7 MB of archives.\nAfter this operation, 240 MB of additional disk space will be used.\nWARNING: The following packages cannot be authenticated!\n  mysql-common mysql-community-client-core mysql-community-client mysql-client\n  mysql-community-server-core mysql-community-server mysql-server\nSetting up remote connections for root user\n\n---errout---\n\nWARNING: apt does not have a stable CLI interface. Use with caution in scripts.\n\ndebconf: unable to initialize frontend: Dialog\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\ndebconf: falling back to frontend: Readline\ndebconf: unable to initialize frontend: Readline\ndebconf: (This frontend requires a controlling tty.)\ndebconf: falling back to frontend: Teletype\ndpkg-preconfigure: unable to re-open stdin: \ngpg: requesting key 5072E1F5 from hkp server keys.gnupg.net\ngpg: keyserver timed out\ngpg: keyserver receive failed: keyserver error\nW: GPG error: http://repo.mysql.com/apt/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8C718D3B5072E1F5\nW: The repository 'http://repo.mysql.com/apt/ubuntu xenial InRelease' is not signed.\ndebconf: unable to initialize frontend: Dialog\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\ndebconf: falling back to frontend: Readline\ndebconf: unable to initialize frontend: Readline\ndebconf: (This frontend requires a controlling tty.)\ndebconf: falling back to frontend: Teletype\ndpkg-preconfigure: unable to re-open stdin: \n\nWARNING: apt does not have a stable CLI interface. Use with caution in scripts.\n\nE: There were unauthenticated packages and -y was used without --allow-unauthenticated\ninstall_MySQL8.sh: line 47: mysql: command not found\ninstall_MySQL8.sh: line 53: mysql: command not found\nsed: can't read /etc/mysql/mysql.conf.d/mysqld.cnf: No such file or directory\nFailed to restart mysql.service: Unit mysql.service not found.\n\n"
      }
    ]
  }
}'"

**Hardware**
HP DL380 Gen9 

**Send the logs**
Zip up your ConfigASDK\Logs folder and send them to asdkconfigurator @ outlook .com and I'll analyze them as quickly as possible.

**Additional context**

**Comment by mattmcspirit** [comment]
Hey, was this an online deployment, i.e. you didn't use the ZIP file?

**Comment by caaustin74** [comment]
Hi, 

Yes this was an online deployment.

thank you,

C

**Comment by mattmcspirit** [comment]
Thanks - leave it with me!

**Comment by mattmcspirit** [comment]
Hey, i'm going to close this, as i think it may have been a transient issue - I've retested twice and it seems to be fine.  May have just been an issue with the Repo Key Server:

_requesting key 5072E1F5 from hkp server keys.gnupg.net\ngpg: keyserver timed out\ngpg: keyserver receive failed: keyserver error\nW: GPG error: http://repo.mysql.com/apt/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8C718D3B5072E1F5\nW_

Seems to be working fine at the moment.

Thanks for letting me know!
Matt
