### ISSUE TITLE
Portals Inaccessible...

### ISSUE THREAD

**Issue by dreampost** [mattmcspirit/azurestack#125]
I tried scenario 1 and scenario 3 for this and they all end with the same result: 
name resolution for adminportal.local.azurestack.external and the normal portal fails.

**Comment by mattmcspirit** [comment]
Hi - so if name resolution isn't working for you, one of two things are going on:

- Either your environment hasn't deployed correctly, or has encountered an issue after deployment
- You haven't deployed the ASDK yet

For the 2nd one, remember, my script can only be used **after** you've deployed your ASDK, it won't deploy the ASDK for you.

Please make sure you've done the following:

1) Downloaded the ASDK and extracted
2) Prepare the ASDK host: https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-prepare-host?view=azs-2002
3) Install the ASDK: https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-install?view=azs-2002
4) Then run my script once the ASDK deployment has completed.

If you have deployed the ASDK, and stuff just isn't working, I'd consider rebooting the ASDK host system to see if that brings the portals and other systems back online.

Thanks,
Matt
