### ISSUE TITLE
Migrate PowerShell scripts from AzureRM to the Az PowerShell module

### ISSUE THREAD

**Issue by rfsonders** [mattmcspirit/azurestack#130]
**Describe the issue**

The requirement ask is to upgrade the trunk to reflect the Az PowerShell modules. Migrating from AzureRM.
https://docs.microsoft.com/en-us/powershell/azure/quickstart-migrate-azurerm-to-az-automatically?view=azps-5.0.0
Attached is the PowerShell Upgrade Report.

I am open to contributing cycles to work through the migration cleanup and subsequent testing. I am curious if the rest of the community is on board and can help.

I personally find Matt's tooling high value for our ASDK deployment and customer demos. Who else feels the same and would like to help modernize the tooling?

[PowerShellUpgradePlan.xlsx](https://github.com/mattmcspirit/azurestack/files/5550906/PowerShellUpgradePlan.xlsx)

**Comment by rfsonders** [comment]
Hello Matt.
 @sqltechmike just forked your project. We will start working on the PowerShell migration. Then submit for your approval.

**Comment by mattmcspirit** [comment]
Sounds great, thanks - I'll likely merge it into a dev branch and then test myself also.  There's changes I will need to make that go beyond the PS modules - SQL/MySQL for instance now need a marketplace-only image, so there's work to do to figure that out among other things.

Thanks!

**Comment by rfsonders** [comment]
Hello Matt.
Our goal - with our branch - would be to merge back into your Master. We have made decent progress already but slowed a bit by scripts from the App Services teams. Code that does not yet support Az PS.
These types of issues may also take collaboration from you and your wider team. Do you have any thoughts as to the best path forward, to collaborate, shore up your master branch and not duplicate efforts?

In the end, your AzSPoC solution is extremely valuable to us and many. The community should help you maintain - which is where we would like to contribute.
Thank you!

**Comment by mattmcspirit** [comment]
I'd say continue to work on your forked version, then when you get to a logical point, merge it into a 2008 branch in my repo, which we can collectively work on, before pushing to master.  Once this major 2008 update is fixed, maintaining going forward should be easier.

As for App Service, i'm suprised this needs much work - usually I just call the silent installer and the JSON file, and it handles the rest.  What issue are you seeing, and with which part of the App Service process?  Pre-reqs, or deployment?

**Comment by mattmcspirit** [comment]
This should now be fixed in the latest release.
