### ISSUE TITLE
ASDK configuration issue

### ISSUE THREAD

**Issue by akn9050** [mattmcspirit/azurestack#137]
**Describe the issue**
Few Jobs are failing and not working on re-running the script. Please find teh error message from Powershell window: 
****** DO NOT CLOSE THIS SESSION - If you do, please run .\GetJobStatus.ps1 from within C:\AzSPoC\Scripts to resume job monitoring ******
****** Please wait until all jobs have completed/failed before re-running the main script ******
At least one of the jobs failed.
FAILED JOB: Job Name: DownloadWindowsUpdates | Error Message: You cannot call a method on a null-valued expression.
FAILED JOB: Job Name: AddServerCore2016Image | Error Message: The WindowsUpdates stage of the process has failed. This is required before the Windows Server images can be created. Check the WindowsUpdates log, ensure that step is completed first, and rerun.
FAILED JOB: Job Name: AddServerFull2016Image | Error Message: The WindowsUpdates stage of the process has failed. This is required before the Windows Server images can be created. Check the WindowsUpdates log, ensure that step is completed first, and rerun.
FAILED JOB: Job Name: AddSQLServerRP | Error Message: ScriptHalted
FAILED JOB: Job Name: AddSQLServerSku | Error Message: The SQLServerRP stage of the process has failed. This should fully complete before the SKU and Quota are created. Check the SQLServerRP log, ensure that step is completed first, and rerun.
FAILED JOB: Job Name: AddSQLHosting | Error Message: The SQLServerSKUQuota stage of the process has failed. This should fully complete before the SQLServer database host has been deployed. Check the SQLServerSKUQuota log, ensure that step is completed first, and rerun.
FAILED JOB: Job Name: DeployAppServiceFS | Error Message: The ServerCore2016Image stage of the process has failed. This should fully complete before the File Server can be deployed. Check the ServerFullImage log, ensure that step is completed first, and rerun.
FAILED JOB: Job Name: DeployAppService | Error Message: Deploying the App Service Resource Provider failed after 3 attempts. Check the logs and rerun the script
[7:11 PM]::[LAUNCHJOBS]:: Please review the logs for further troubleshooting.Exception.Message

**Hardware**
Please provide details about your hardware environment, such as HDDs/SSDs, # of CPUs, RAM and whether this is physical, or a nested VM in Azure etc.
Azure Vm Size: Standard   E20s_v3 (20 vcpus, 160 GiB memory), 
OS DIsk: 256 SSD
Data Disk: 6*256 SSD
--

**Send the logs**
Zip up your ConfigASDK\Logs folder and send them to asdkconfigurator @ outlook .com and I'll analyze them as quickly as possible.
sent the logs on mail

**Additional context**

**Comment by mattmcspirit** [comment]
Hi Amit - can you hang on a few more days? I have an update that i'll likely publish tomorrow that fixes all these things. I'm just in the final stages of testing. Above, the Windows Updates stage is failing, causing subsequent steps to fail.

**Comment by akn9050** [comment]
Hi Matt, Thanks for the quick response :) ,I would like to try out the fixes tomorrow.

**Comment by mattmcspirit** [comment]
Assuming it passes all remaining tests, you'll see an updated build published.  Thanks!

**Comment by akn9050** [comment]
Hi Matt, are you pushing updates today?

**Comment by mattmcspirit** [comment]
Hi Amit,

Please understand that working on this isn't part of my primary role any longer, so all I can offer is, it'll be ready when it's ready - I'm sorry if this causes inconvenience but I'm working on this in my limited spare time.  I don't have cycles to offer support and ongoing fixes unfortunately, so this will likely be the last major push.  Thanks for your understanding.

**Comment by mattmcspirit** [comment]
This should now be fixed in the latest release.
