### ISSUE TITLE
Issue #0011 : Registration token is malformed. 

### ISSUE THREAD

**Issue by ainsalleh** [mattmcspirit/azurestack#140]
**Describe the issue**
Hi, I'm having an issue when running your script. It's stuck at creating Azure Resource. I've tried re-running multiple times and still receiving the same error. Please refer the log file sent to asdkconfigurator @ outlook .com

**Hardware**
I run the script on nested vm on Hyper-V. The ASDK host disks are as shown in the zip file

**Send the logs**
Zip up your ConfigASDK\Logs folder and send them to asdkconfigurator @ outlook .com and I'll analyze them as quickly as possible.

**Additional context**

**Comment by mattmcspirit** [comment]
Adding @SqlTechMike to see if he's seen this. I don't have bandwidth for investigating right now I'm afraid, however if you're using the 2102 build, it may be worth testing one of these options:

Assuming you have the correct permissions in Azure for your subscription:

- Update your PS modules manually and retry: https://docs.microsoft.com/en-us/azure-stack/operator/powershell-install-az-module?view=azs-2102
- If that doesn't work, try the registration manually following the steps here: https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-registration?view=azs-2102&tabs=az1%2Caz2%2Caz3%2Caz4&pivots=state-connected
- if that doesn't work, this seems to be similar to your issue, with a documented workaround: https://github.com/Azure/AzureStack-Tools/issues/597

Thanks,
Matt

**Comment by ainsalleh** [comment]
Hi Mattmcspirit/Azurestack

Thank you for your feedback. I've done updating the module and registered
manually. Now following the third alternative and the registration was
successful. Do you perhaps want to add some note in your readme to avoid
this issue again in the future?

**Comment by mattmcspirit** [comment]
Thanks for this - so to confirm:

1) Updating the modules did **not** fix anything
2) Registering manually did **not** work
3) Following the workaround **did** work

Thanks!
Matt

**Comment by ainsalleh** [comment]
Yes, that is correct.

**Comment by mattmcspirit** [comment]
Thanks - updated the known issues with a link to the workaround.
