### ISSUE TITLE
AppServicePreDeploymentSettings.json has Typo

### ISSUE THREAD

**Issue by CRachfahl** [mattmcspirit/azurestack#22]
Hi Matt,

great work. I found a typo in the AppServicePreDeploymentSettings.json file. The Parameter:

"ResouceProviderPfxCertPath"   ->   "ResourceProviderPfxCertPath"
"ResouceProviderPfxCertPassword"  ->  "ResourceProviderPfxCertPassword" 

thanks for the great work

Carsten Rachfahl

**Comment by mattmcspirit** [comment]
Thanks Carsten!  Now fixed! I can't believe I missed this, but I suspect it didn't get picked up for AppService 1.1, but does for 1.2.  Should work now...!

**Comment by CRachfahl** [comment]
Hi Matt, 

yes it works now!

Carsten
