### ISSUE TITLE
fileserver fails to deploy

### ISSUE THREAD

**Issue by vniklas** [mattmcspirit/azurestack#26]
![image](https://user-images.githubusercontent.com/11834100/40844749-0829b67c-65b5-11e8-95f4-a05593742e6d.png)

AppServiceFileServer       Failed
AppServiceSQLServer        Incomplete
DownloadAppService         Incomplete
GenerateAppServiceCerts    Incomplete
CreateServicePrincipal     Incomplete
GrantAzureADAppPermissions Incomplete
InstallAppService          Incomplete
InstallHostApps            Incomplete
CreateOutput               Incomplete
VERBOSE: 3:03:52 PM - Resource Microsoft.Compute/virtualMachines 'fileserver' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VmProvisioningTimeout",
        "message": "VM 'fileserver' failed to provision with timeout."
      }
    ]
  }
}'

It seems to be some error, I have tried to remove the failed fileserver and rerun the script but same error again...

**Comment by mattmcspirit** [comment]
Hmm, I haven't seen a fileserver provisioning issue before. Does the VM and other artifacts get deployed within the RG, such as the nic, vNet etc? What do the audit logs in the portal say? No one else has mentioned that error before and I've never seen the fileserver deployment fail. Feel free to email me any logs (remove your sensitive info like pwds etc) and i'll take a look. May take me a few days as I'm on vacation. Did your MySQL/SQL RP's deploy fine?  They use the Server Core image, and i think the fileserver uses Full, so there may be an issue with the image I guess. Can you test a standard deployment from your WS full image to ensure it works correctly? Perhaps it's the DSC that's timing out, but I'm not sure why.

Share any extra relevant info and we'll troubleshoot. My script simply executes this template https://raw.githubusercontent.com/mattmcspirit/azurestack/master/deployment/templates/FileServer/azuredeploy.json, so nothing really special about the deployment.
