### ISSUE TITLE
Says my account is a Microsoft Account

### ISSUE THREAD

**Issue by kristopherjturner** [mattmcspirit/azurestack#27]
I am getting the following error below.  The account I am using is an Organization account and not a Microsoft account.

Testing Azure Login:  

PS>TerminatingError(Add-AzureRmAccount): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: -Credential parameter can only be used with Organization ID credentials. For more information, please refer to http://go.microsoft.com/fwlink/?linkid=331007&clcid=0x409 for more information about the difference between an organizational account and a Microsoft account."
VERBOSE: -Credential parameter can only be used with Organization ID credentials. For more information, please refer to http://go.microsoft.com/fwlink/?linkid=331007&clcid=0x409 for more information about the difference between an organizational account and a Microsoft account.

**Comment by kristopherjturner** [comment]
Never mind the bearded larger man in the corner....   :)   I figured it out.  Was a normal ID 10 T error.  I had the wrong password for the azureAdPwd parameter.  

Just walked through it manually and took me a few tries before the light bulb came on.  

Thanks for your hard work here.

**Comment by mattmcspirit** [comment]
Thanks Kristopher - strange error message though, quite misleading! I actually thought it was referring to this issue: https://github.com/Azure/azure-powershell/issues/4016 but thankfully, you've got past that. Hope it worked ok!?  Thanks!
