### ISSUE TITLE
Error at Ubuntu Image Stage - 1805.2 Version

### ISSUE THREAD

**Issue by kristopherjturner** [mattmcspirit/azurestack#30]
I am playing with this new version for 1805.  I ran into an issue on the ubuntu image stage:

>> TerminatingError(Invoke-RestMethod): "{"error":{"code":"ParentResourceNotFound","message":"Can not perform requested operation on nested resource. Parent resource 'AzureStack-VNET' not found."}}"
VERBOSE: [6:51 PM]::[UBUNTUIMAGE]:: ASDK Configuration Stage: UbuntuImage Failed

I will dig into this more but wanted to post this just in case it was an easy fix.

**Comment by kristopherjturner** [comment]
Yes, I have tried it a few times.  I am wondering if the Get command is incorrect?  That shows in the logs right before it terminates.  

VERBOSE: GET https://management.azure.com/subscriptions/f9eaaf80-8490-4b69-88fd-a168ec890221/resourceGroups/azurestack/providers/Microsoft.AzureStack/registrations/AzureStack-VNET/products?api-version=2016-01-01 with 0-byte payload

**Comment by mattmcspirit** [comment]
That is strange. If you chose to register your ASDK as part of the process, it normally creates a resource in Azure called azurestack. This is created by the registration module, not my script per se. I'm confused why this 'AzureStack-VNET' is being created. The registration section and the Ubuntu image section hasn't really change for multiple releases. I wonder if you should log into Azure portal, remove "Azurestack-vNet" if its not being used for anything, then I'd manually edit the progress.CSV file in your Azure Stack download folder and set the registration step as Incomplete.

I think something is mixed up there but I can't be certain without looking into it a bit more.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by kristopherjturner** [comment]
Interesting.  I did confirm there was a vnet on that subscription called AzureStack-vNet.  I am also playing with automation of ASDK on Azure VM's just to spin one up on an E series for a few days for demos.  The ARM I am using creates that.  I will delete that vnet and registration to the other ASDK and re-run your script.

**Comment by kristopherjturner** [comment]
Got it.  I changed the -aureRegSubID to another subscription.  However, that brings up a question now, it would have registered using that first subscription I had in the script, correct?  

The first few times I ran the script with the subscription:  f9eaaf80-8490-4b69-88fd-a168ec890221

However, I just looked at the logs and it registered the ASDK with another subscription in my Tenant. Once I changed the -azureRegSubID to the actual subscription it had registered under it is now working. 

I guess we just need to make sure the subscription we put for that parameter doesn't already have an ASDK registered to it?

**Comment by mattmcspirit** [comment]
It shouldn't be an issue to have a subscription with an existing registration, I do it all the time. Each fresh ASDK should just create a new resource in that subscription for the registration of that ASDK.

So when you ran the script, it will (should) firstly attempt to sign you in based on your tenant name and login credentials. These will be the same creds you used at deployment time for the ASDK. If you used the -registerASDK switch, along with the -useSameCreds switch, and specified the corresponding same subscription, it should have just worked.

I wonder if I need to rethink this subscription thing. Perhaps a better solution would be to ask for the subscriptionID up front, associated with the deployment of the ASDK. If people choose -registerASDK and -UseSameCreds, it will register to that sub, grabbing the tenantID for that sub. It will only use a different sub and creds if you don't specify -useSameCreds and -azureRegSubId.

I'll have to have a play around. This is the biggest challenge, testing against scenarios that I don't have in my environment! It usually affects people who have multiple AD tenants and subs associated with a single set of credentials. I have set that up in my environment to test but I must be missing something.

The account and creds you used to sign in - how many Azure Ad directories do you have access to with that account, and how many subs?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by kristopherjturner** [comment]
It all worked.  Thanks.

**Comment by mattmcspirit** [comment]
Great! For reference, how many subs and tenant directories does your login creds give you access to? I'd like to try to recreate your setup in my subs/tenants so I can reduce the chance for errors if possible! If you could use examples like:

Sub A - tenant A, (directory role: global Admin)

If you prefer email, that works also, just let me know.

Thanks Kris!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
