### ISSUE TITLE
Typo at line 1692

### ISSUE THREAD

**Issue by devalian** [mattmcspirit/azurestack#34]
$packageArray = "*Microsoft.WindowsServer2016Datacenter-ARM*", "*Microsoft.WindowsServer2016DatacenterCore-ARM*"

Corrected version is as below:
$packageArray = "*Microsoft.WindowsServer2016Datacenter-ARM*", "*Microsoft.WindowsServer2016Datacenter**Server**Core-ARM*"

**Comment by devalian** [comment]
Line 1708 , got some script logic issue. 
                $Upload = Add-AzsGalleryItem -GalleryItemUri $galleryItemUri -Force -Confirm:$false -ErrorAction Stop

$galleryItemUri is somehow empty for me. and the logic indeed doesnt populate the items for gallery to be uploaded. which relate to my title, where servercore is missing and unable to upload.

**Comment by mattmcspirit** [comment]
Thank you! I think the names of the Server Core marketplace item changed slightly in the official marketplace - I'll update the logic shortly. If you want to make the change that you added in your first post, in your ConfigAsdk.ps1 file, and rerun the script, it should pick up from there. Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by devalian** [comment]
Great to hear from you @mattmcspirit. the scripts seems to be running good for me, after 2 changes i highlighted above. will update if i bump into anything else. 

cheers!

**Comment by mattmcspirit** [comment]
Awesome, thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by mattmcspirit** [comment]
Should be fixed and live now!  New version coming soon too! :)
