### ISSUE TITLE
Examples need (some) fixing

### ISSUE THREAD

**Issue by TomicaKaniski** [mattmcspirit/azurestack#40]
Hello Matt,

Your examples need a small fix - your ISO path is not "D:\WS2016EVALISO.iso", rather "D:\ASDKFiles\WS2016EVALISO.iso". Awesome work, btw!

Cheers,
Tom

**Comment by mattmcspirit** [comment]
Hi Tomica, 

Thanks for this, however the examples are correct - for the online deployments, your ISO file can live anywhere on your system - it doesn't need to be within your -downloadFolder

Thanks!
Matt
