### ISSUE TITLE
Script stuck at setting up MySQLDBVM

### ISSUE THREAD

**Issue by RiversC** [mattmcspirit/azurestack#42]
_VERBOSE: 8:20:00 PM - Resource Microsoft.Compute/virtualMachines 'mysqlhost' provisioning status is succeeded
VERBOSE: 8:20:00 PM - Checking deployment status in 5 seconds
VERBOSE: 8:20:05 PM - Checking deployment status in 5 seconds
VERBOSE: 8:20:11 PM - Resource Microsoft.Compute/virtualMachines/extensions 'mysqlhost/CustomScriptExtension'
provisioning status is running
VERBOSE: 8:20:11 PM - Checking deployment status in 5 seconds
VERBOSE: 8:20:17 PM - Checking deployment status in 5 seconds
VERBOSE: 8:20:23 PM - Checking deployment status in 5 seconds
VERBOSE: 8:20:28 PM - Checking deployment status in 5 seconds
VERBOSE: 8:20:34 PM - Checking deployment status in 5 seconds
VERBOSE: 8:20:40 PM - Checking deployment status in 5 seconds
VERBOSE: 8:20:45 PM - Checking deployment status in 5 seconds
VERBOSE: 8:20:51 PM - Checking deployment status in 5 seconds
VERBOSE: 8:20:57 PM - Checking deployment status in 5 seconds
VERBOSE: [8:21 PM]::[MYSQLDBVM]:: ASDK Configuration Stage: MySQLDBVM Failed

Stage                      Status
-----                      ------
ExtractZip                 Skipped
InstallPowerShell          Complete
DownloadTools              Complete
HostConfiguration          Complete
Registration               Skipped
UbuntuImage                Complete
WindowsImage               Complete
MySQLGalleryItem           Complete
SQLServerGalleryItem       Complete
VMExtensions               Skipped
MySQLRP                    Complete
SQLServerRP                Complete
MySQLSKUQuota              Complete
SQLServerSKUQuota          Complete
UploadScripts              Skipped
MySQLDBVM                  Failed
SQLServerDBVM              Incomplete
MySQLAddHosting            Incomplete
SQLServerAddHosting        Incomplete
AppServiceFileServer       Incomplete
AppServiceSQLServer        Incomplete
DownloadAppService         Incomplete
GenerateAppServiceCerts    Incomplete
CreateServicePrincipal     Incomplete
GrantAzureADAppPermissions Incomplete
InstallAppService          Incomplete
RegisterNewRPs             Incomplete
CreatePlansOffers          Incomplete
InstallHostApps            Incomplete
CreateOutput               Incomplete

VERBOSE: [8:21 PM]::[MYSQLDBVM]:: 8:21:03 PM - Resource Microsoft.Compute/virtualMachines/extensions
'mysqlhost/CustomScriptExtension' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'CustomScriptExtension'. Error message:
Malformed status file [ExtensionError] Invalid status/status: failed"
      }
    ]
  }
}'.Exception.Message_

The script stops here and won't progress any further.  Unsure of where to start troubleshooting the issue...

**Comment by mattmcspirit** [comment]
Hey - could you log into the Azure Stack Admin Portal, delete the resource group that contains the MySQLDBVM, and the rerun the script with the same command as before? Let me know if it fails again, and I'll investigate. It looks as if it's reaching the stage where it's executing the custom script at the end of the deployment process, and trying to install MySQL, and encountering an issue.  There are logs within the VM that would explain the issue, but for now, let's try cleaning and restarting and if it fails again, we'll look inside the VM at the Custom Script Extension logs.

Thanks!
Matt

**Comment by RiversC** [comment]
Will try that.  Just confirming that I am deleting the correct RG.



 

Christopher Rivers

Director, Information Technology | Directeur des technologies de l'information

Canadian Museum for Human Rights | Musée canadien pour les droits de la personne

**Comment by RiversC** [comment]
The image didn't come through...I have two RGs that look like they might be the right one:

**azurestack-dbhosting** and **system.local.mysqladapter**

**Comment by mattmcspirit** [comment]
Hi Christopher - it should be the azurestack-dbhosting RG.

Could i also ask, is this deployment connected to the internet? I presume so, but wanted to check. The MySQL installer (which runs at the end of the VM deployment process) tries to do a Apt-Get Update, and also pulls the MySQL files from the Ubuntu repos (script is here: https://github.com/mattmcspirit/azurestack/blob/master/deployment/scripts/install_MySQL.sh) so if these get blocked by your firewall, I suspect the script would fail and you'd see the error you're seeing.

**Comment by RiversC** [comment]
Deleting that RG and rerunning the script.  Will keep you posted.

Yes, this ASDK is on the internet.  I will have my firewall team check to see if they see that traffic being blocked.

**Comment by mattmcspirit** [comment]
Great, let me know.  If it fails again, if you could install Putty on yoru ASDK host, establish an SSH connection to the VM (the VM will be running and accessible) and we'll check the logs to see where the script is failing.  Thanks for letting me know!

**Comment by RiversC** [comment]
Firewall team reports that the last block from that IP was yesterday (Ubuntu download); I have since torn the ASDK down and rebuilt it and started fresh this morning.

The RG is still deleting so I will have to pick this up tomorrow.

Thanks,
Chris

**Comment by mattmcspirit** [comment]
No worries. In addition, you could deploy a standard Ubuntu VM in your Azure Stack (you should have an Ubuntu 16.04 gallery item available in your portal) and once deployed, putty into it and run a couple of the commands, such as:

sudo apt-get update -y
apt-get -y install mysql-server-5.7 mysql-client

This would show you first hand if the VM can reach the internet, specifically those resources.

If those commands are successful on that VM, delete it and clean up the RG, and we'll focus back on the VM that my script deploys as something script related must be going on. :)

Keep me posted!

Thanks!
Matt

**Comment by RiversC** [comment]
The resource group was deleted overnight and I kicked off the script again this morning but am now getting the following:

_VERBOSE: Performing operation ListWithHttpMessagesAsync on $GalleryAdminClient.
VERBOSE: Operation completed successfully.
VERBOSE: [2:46 PM]::[MYSQLDBVM]:: Creating a dedicated MySQL5.7 on Ubuntu VM for database hosting
VERBOSE: Performing the operation "Creating Deployment" on target "azurestack-dbhosting".
VERBOSE: 2:46:13 PM - Template is valid.
VERBOSE: 2:46:13 PM - Create template deployment 'MySQLHost'
VERBOSE: 2:46:13 PM - Checking deployment status in 5 seconds
VERBOSE: 2:46:19 PM - Checking deployment status in 5 seconds
VERBOSE: 2:46:24 PM - Checking deployment status in 5 seconds
VERBOSE: 2:46:29 PM - Resource Microsoft.Resources/deployments 'ProvisioningPublicIPs' provisioning status is running
VERBOSE: 2:46:29 PM - Checking deployment status in 5 seconds
VERBOSE: 2:46:34 PM - Resource Microsoft.Resources/deployments 'ProvisioningStorageAccount' provisioning status is
running
VERBOSE: 2:46:34 PM - Resource Microsoft.Resources/deployments 'ProvisioningNetworkSecurityGroup' provisioning status
is running
VERBOSE: 2:46:34 PM - Checking deployment status in 5 seconds
VERBOSE: 2:46:40 PM - Resource Microsoft.Storage/storageAccounts 'mysqlstor' provisioning status is running
VERBOSE: 2:46:40 PM - Resource Microsoft.Network/networkSecurityGroups 'mysqlhost_nsg' provisioning status is running
VERBOSE: 2:46:40 PM - Resource Microsoft.Network/publicIPAddresses 'mysql_ip' provisioning status is succeeded
VERBOSE: 2:46:40 PM - Checking deployment status in 5 seconds
VERBOSE: 2:46:45 PM - Checking deployment status in 5 seconds
VERBOSE: 2:46:51 PM - Resource Microsoft.Storage/storageAccounts 'mysqlstor' provisioning status is succeeded
VERBOSE: 2:46:51 PM - Resource Microsoft.Network/networkSecurityGroups 'mysqlhost_nsg' provisioning status is succeeded
VERBOSE: 2:46:51 PM - Resource Microsoft.Resources/deployments 'ProvisioningPublicIPs' provisioning status is succeeded
VERBOSE: 2:46:51 PM - Checking deployment status in 5 seconds
VERBOSE: 2:46:56 PM - Checking deployment status in 5 seconds
VERBOSE: 2:47:02 PM - Resource Microsoft.Resources/deployments 'ProvisioningStorageAccount' provisioning status is
succeeded
VERBOSE: 2:47:02 PM - Resource Microsoft.Resources/deployments 'ProvisioningNetworkSecurityGroup' provisioning status
is succeeded
VERBOSE: 2:47:02 PM - Checking deployment status in 5 seconds
VERBOSE: 2:47:07 PM - Resource Microsoft.Resources/deployments 'ProvisioningVirtualNetwork' provisioning status is
running
VERBOSE: 2:47:07 PM - Checking deployment status in 5 seconds
VERBOSE: 2:47:13 PM - Checking deployment status in 5 seconds
VERBOSE: 2:47:18 PM - Resource Microsoft.Network/virtualNetworks 'dbhosting_vnet' provisioning status is running
VERBOSE: 2:47:18 PM - Checking deployment status in 5 seconds
VERBOSE: 2:47:24 PM - Checking deployment status in 5 seconds
VERBOSE: 2:47:30 PM - Resource Microsoft.Network/virtualNetworks 'dbhosting_vnet' provisioning status is succeeded
VERBOSE: 2:47:30 PM - Checking deployment status in 5 seconds
VERBOSE: 2:47:35 PM - Checking deployment status in 5 seconds
VERBOSE: 2:47:41 PM - Checking deployment status in 5 seconds
VERBOSE: 2:47:46 PM - Resource Microsoft.Resources/deployments 'ProvisioningVirtualNetwork' provisioning status is
succeeded
VERBOSE: 2:47:46 PM - Checking deployment status in 5 seconds
VERBOSE: 2:47:52 PM - Checking deployment status in 5 seconds
VERBOSE: 2:47:58 PM - Resource Microsoft.Network/networkInterfaces 'mysqlhost_nic' provisioning status is succeeded
VERBOSE: 2:47:58 PM - Checking deployment status in 5 seconds
VERBOSE: 2:48:04 PM - Resource Microsoft.Resources/deployments 'ProvisioningVirtualMachine' provisioning status is
running
VERBOSE: 2:48:04 PM - Checking deployment status in 5 seconds
VERBOSE: 2:48:09 PM - Checking deployment status in 5 seconds
VERBOSE: 2:48:15 PM - Resource Microsoft.Storage/storageAccounts 'mysqlstor' provisioning status is succeeded
VERBOSE: 2:48:15 PM - Checking deployment status in 5 seconds
VERBOSE: 2:48:21 PM - Resource Microsoft.Compute/virtualMachines 'mysqlhost' provisioning status is running
VERBOSE: 2:48:21 PM - Checking deployment status in 5 seconds
VERBOSE: 2:48:26 PM - Checking deployment status in 5 seconds
VERBOSE: 2:48:32 PM - Checking deployment status in 5 seconds
VERBOSE: 2:48:38 PM - Checking deployment status in 5 seconds
VERBOSE: 2:48:43 PM - Checking deployment status in 5 seconds
VERBOSE: 2:48:49 PM - Checking deployment status in 5 seconds
VERBOSE: 2:48:55 PM - Checking deployment status in 5 seconds
VERBOSE: 2:49:00 PM - Checking deployment status in 5 seconds
VERBOSE: 2:49:06 PM - Checking deployment status in 5 seconds
VERBOSE: 2:49:12 PM - Checking deployment status in 5 seconds
VERBOSE: 2:49:18 PM - Checking deployment status in 5 seconds
VERBOSE: 2:49:23 PM - Checking deployment status in 5 seconds
VERBOSE: 2:49:29 PM - Checking deployment status in 5 seconds
VERBOSE: 2:49:35 PM - Checking deployment status in 5 seconds
VERBOSE: 2:49:40 PM - Checking deployment status in 5 seconds
VERBOSE: 2:49:46 PM - Checking deployment status in 5 seconds
VERBOSE: 2:49:52 PM - Checking deployment status in 5 seconds
VERBOSE: 2:49:57 PM - Checking deployment status in 5 seconds
VERBOSE: 2:50:03 PM - Checking deployment status in 5 seconds
VERBOSE: 2:50:09 PM - Checking deployment status in 5 seconds
VERBOSE: 2:50:14 PM - Checking deployment status in 5 seconds
VERBOSE: 2:50:20 PM - Checking deployment status in 5 seconds
VERBOSE: 2:50:26 PM - Checking deployment status in 5 seconds
VERBOSE: 2:50:31 PM - Checking deployment status in 5 seconds
VERBOSE: 2:50:37 PM - Checking deployment status in 5 seconds
VERBOSE: 2:50:43 PM - Checking deployment status in 5 seconds
VERBOSE: 2:50:49 PM - Checking deployment status in 5 seconds
VERBOSE: 2:50:54 PM - Checking deployment status in 5 seconds
VERBOSE: 2:51:00 PM - Checking deployment status in 5 seconds
VERBOSE: 2:51:06 PM - Checking deployment status in 5 seconds
VERBOSE: 2:51:11 PM - Checking deployment status in 5 seconds
VERBOSE: 2:51:17 PM - Checking deployment status in 5 seconds
VERBOSE: 2:51:23 PM - Checking deployment status in 5 seconds
VERBOSE: 2:51:28 PM - Checking deployment status in 5 seconds
VERBOSE: 2:51:34 PM - Checking deployment status in 5 seconds
VERBOSE: 2:51:40 PM - Checking deployment status in 5 seconds
VERBOSE: 2:51:46 PM - Checking deployment status in 5 seconds
VERBOSE: 2:51:51 PM - Checking deployment status in 5 seconds
VERBOSE: 2:51:57 PM - Checking deployment status in 5 seconds
VERBOSE: 2:52:03 PM - Checking deployment status in 5 seconds
VERBOSE: 2:52:08 PM - Checking deployment status in 5 seconds
VERBOSE: 2:52:14 PM - Checking deployment status in 5 seconds
VERBOSE: 2:52:20 PM - Checking deployment status in 5 seconds
VERBOSE: 2:52:25 PM - Checking deployment status in 5 seconds
VERBOSE: 2:52:31 PM - Checking deployment status in 5 seconds
VERBOSE: 2:52:37 PM - Checking deployment status in 5 seconds
VERBOSE: 2:52:42 PM - Resource Microsoft.Compute/virtualMachines 'mysqlhost' provisioning status is succeeded
VERBOSE: 2:52:42 PM - Checking deployment status in 5 seconds
VERBOSE: 2:52:48 PM - Checking deployment status in 5 seconds
VERBOSE: 2:52:54 PM - Resource Microsoft.Compute/virtualMachines/extensions 'mysqlhost/CustomScriptExtension'
provisioning status is running
VERBOSE: 2:52:54 PM - Checking deployment status in 5 seconds
VERBOSE: 2:53:00 PM - Checking deployment status in 5 seconds
VERBOSE: 2:53:06 PM - Checking deployment status in 5 seconds
VERBOSE: 2:53:12 PM - Checking deployment status in 5 seconds
VERBOSE: 2:53:17 PM - Checking deployment status in 5 seconds
VERBOSE: 2:53:23 PM - Checking deployment status in 5 seconds
VERBOSE: 2:53:29 PM - Checking deployment status in 5 seconds
VERBOSE: 2:53:34 PM - Checking deployment status in 5 seconds
VERBOSE: 2:53:40 PM - Checking deployment status in 5 seconds
VERBOSE: 2:53:46 PM - Checking deployment status in 5 seconds
VERBOSE: 2:53:52 PM - Checking deployment status in 5 seconds
VERBOSE: 2:53:57 PM - Checking deployment status in 5 seconds
VERBOSE: 2:54:03 PM - Checking deployment status in 5 seconds
VERBOSE: 2:54:09 PM - Checking deployment status in 5 seconds
VERBOSE: 2:54:14 PM - Checking deployment status in 5 seconds
VERBOSE: 2:54:20 PM - Checking deployment status in 5 seconds
VERBOSE: 2:54:26 PM - Checking deployment status in 5 seconds
VERBOSE: 2:54:31 PM - Checking deployment status in 5 seconds
VERBOSE: 2:54:37 PM - Checking deployment status in 5 seconds
VERBOSE: 2:54:43 PM - Checking deployment status in 5 seconds
VERBOSE: 2:54:49 PM - Checking deployment status in 5 seconds
VERBOSE: 2:54:54 PM - Checking deployment status in 5 seconds
VERBOSE: [2:55 PM]::[MYSQLDBVM]:: ASDK Configuration Stage: MySQLDBVM Failed

Stage                      Status
-----                      ------
ExtractZip                 Skipped
InstallPowerShell          Complete
DownloadTools              Complete
HostConfiguration          Complete
Registration               Skipped
UbuntuImage                Complete
WindowsImage               Complete
MySQLGalleryItem           Complete
SQLServerGalleryItem       Complete
VMExtensions               Skipped
MySQLRP                    Complete
SQLServerRP                Complete
MySQLSKUQuota              Complete
SQLServerSKUQuota          Complete
UploadScripts              Skipped
MySQLDBVM                  Failed
SQLServerDBVM              Incomplete
MySQLAddHosting            Incomplete
SQLServerAddHosting        Incomplete
AppServiceFileServer       Incomplete
AppServiceSQLServer        Incomplete
DownloadAppService         Incomplete
GenerateAppServiceCerts    Incomplete
CreateServicePrincipal     Incomplete
GrantAzureADAppPermissions Incomplete
InstallAppService          Incomplete
RegisterNewRPs             Incomplete
CreatePlansOffers          Incomplete
InstallHostApps            Incomplete
CreateOutput               Incomplete


VERBOSE: [2:55 PM]::[MYSQLDBVM]:: 2:55:00 PM - Resource Microsoft.Compute/virtualMachines/extensions
'mysqlhost/CustomScriptExtension' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'CustomScriptExtension'. Error message:
Malformed status file [ExtensionError] Invalid status/status: failed"
      }
    ]
  }
}'.Exception.Message_

**Comment by mattmcspirit** [comment]
OK, looks like the same issue then.

Let's go with my previous suggestion - deploy a standard Ubuntu VM in your Azure Stack (you should have an Ubuntu 16.04 gallery item available in your portal, under New -> Compute and once deployed, Putty into it and run a couple of the commands, such as:
sudo apt-get update -y
apt-get -y install mysql-server-5.7 mysql-client
This would show you first hand if the VM can reach the internet, specifically those resources.
If those commands are successful on that VM, delete it and clean up the RG, and we'll focus back on the VM that my script deploys as something script related must be going on. :)

**Comment by RiversC** [comment]
From either the test VM I created or the MySQLHost VM.  I confirmed I am able to ping 8.8.8.8 from either VM.

I get the following when doing the apt-get update.

W: The repository 'http://security.ubuntu.com/ubuntu xenial-security Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://azure.archive.ubuntu.com/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://azure.archive.ubuntu.com/ubuntu xenial-updates Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://azure.archive.ubuntu.com/ubuntu xenial-backports Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/main/source/Sources  Connection failed [IP: 91.189.91.26 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/dists/xenial/main/source/Sources  Connection failed
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/dists/xenial-updates/main/source/Sources  Connection failed
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/dists/xenial-backports/main/source/Sources  Connection failed
E: Some index files failed to download. They have been ignored, or old ones used instead.

Firewall team reports no blocks and I get a 404 when I attempt to browse to http://azure.archive.ubuntu.com/ubuntu/dists/xenial/main/source/Sources.

**Comment by RiversC** [comment]
mysqladmin@mysqlhost:~$ sudo apt-get -y install mysql-server-5.7 mysql-client
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libaio1 libcgi-fast-perl libcgi-pm-perl libencode-locale-perl libevent-core-2.0-5 libfcgi-perl libhtml-parser-perl libhtml-tagset-perl libhtml-template-perl libhttp-date-perl libhttp-message-perl libio-html-perl
  liblwp-mediatypes-perl libtimedate-perl liburi-perl mysql-client-5.7 mysql-client-core-5.7 mysql-common mysql-server-core-5.7
Suggested packages:
  libdata-dump-perl libipc-sharedcache-perl libwww-perl mailx tinyca
The following NEW packages will be installed:
  libaio1 libcgi-fast-perl libcgi-pm-perl libencode-locale-perl libevent-core-2.0-5 libfcgi-perl libhtml-parser-perl libhtml-tagset-perl libhtml-template-perl libhttp-date-perl libhttp-message-perl libio-html-perl
  liblwp-mediatypes-perl libtimedate-perl liburi-perl mysql-client mysql-client-5.7 mysql-client-core-5.7 mysql-common mysql-server-5.7 mysql-server-core-5.7
0 upgraded, 21 newly installed, 0 to remove and 0 not upgraded.
Need to get 19.4 MB of archives.
After this operation, 162 MB of additional disk space will be used.
Err:1 http://security.ubuntu.com/ubuntu xenial-security/main amd64 mysql-common all 5.7.23-0ubuntu0.16.04.1
  Connection failed
Err:2 http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 libaio1 amd64 0.3.110-2
  Connection failed
Err:1 http://security.ubuntu.com/ubuntu xenial-security/main amd64 mysql-common all 5.7.23-0ubuntu0.16.04.1
  Connection failed
Err:3 http://security.ubuntu.com/ubuntu xenial-security/main amd64 mysql-client-core-5.7 amd64 5.7.23-0ubuntu0.16.04.1
  Connection failed
Ign:4 http://security.ubuntu.com/ubuntu xenial-security/main amd64 mysql-client-5.7 amd64 5.7.23-0ubuntu0.16.04.1
Err:3 http://security.ubuntu.com/ubuntu xenial-security/main amd64 mysql-client-core-5.7 amd64 5.7.23-0ubuntu0.16.04.1
  Connection failed
Ign:5 http://security.ubuntu.com/ubuntu xenial-security/main amd64 mysql-server-core-5.7 amd64 5.7.23-0ubuntu0.16.04.1
Err:4 http://security.ubuntu.com/ubuntu xenial-security/main amd64 mysql-client-5.7 amd64 5.7.23-0ubuntu0.16.04.1
  Connection failed
Ign:6 http://security.ubuntu.com/ubuntu xenial-security/main amd64 libevent-core-2.0-5 amd64 2.0.21-stable-2ubuntu0.16.04.1
Err:5 http://security.ubuntu.com/ubuntu xenial-security/main amd64 mysql-server-core-5.7 amd64 5.7.23-0ubuntu0.16.04.1
  Connection failed
Ign:7 http://security.ubuntu.com/ubuntu xenial-security/main amd64 mysql-server-5.7 amd64 5.7.23-0ubuntu0.16.04.1
Err:6 http://security.ubuntu.com/ubuntu xenial-security/main amd64 libevent-core-2.0-5 amd64 2.0.21-stable-2ubuntu0.16.04.1
  Connection failed
Err:8 http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 libhtml-tagset-perl all 3.20-2
  Connection failed
Err:7 http://security.ubuntu.com/ubuntu xenial-security/main amd64 mysql-server-5.7 amd64 5.7.23-0ubuntu0.16.04.1
  Connection failed
Err:9 http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 liburi-perl all 1.71-1
  Connection failed
Err:10 http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 libhtml-parser-perl amd64 3.72-1
  Connection failed
Err:11 http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 libcgi-pm-perl all 4.26-1
  Connection failed
Err:12 http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 libfcgi-perl amd64 0.77-1build1
  Connection failed
Err:13 http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 libcgi-fast-perl all 1:2.10-1
  Connection failed
Err:14 http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 libencode-locale-perl all 1.05-1
  Connection failed
Err:15 http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 libhtml-template-perl all 2.95-2
  Connection failed
Err:16 http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 libtimedate-perl all 2.3000-2
  Connection failed
Err:17 http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 libhttp-date-perl all 6.02-1
  Connection failed
Err:18 http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 libio-html-perl all 1.001-1
  Connection failed
Err:19 http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 liblwp-mediatypes-perl all 6.02-1
  Connection failed
Err:20 http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 libhttp-message-perl all 6.11-1
  Connection failed
Err:21 http://security.ubuntu.com/ubuntu xenial-security/main amd64 mysql-client all 5.7.23-0ubuntu0.16.04.1
  Connection failed
Err:21 http://security.ubuntu.com/ubuntu xenial-security/main amd64 mysql-client all 5.7.23-0ubuntu0.16.04.1
  Connection failed
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.7/mysql-common_5.7.23-0ubuntu0.16.04.1_all.deb  Connection failed

E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/liba/libaio/libaio1_0.3.110-2_amd64.deb  Connection failed

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.7/mysql-client-core-5.7_5.7.23-0ubuntu0.16.04.1_amd64.deb  Connection failed

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.7/mysql-client-5.7_5.7.23-0ubuntu0.16.04.1_amd64.deb  Connection failed

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.7/mysql-server-core-5.7_5.7.23-0ubuntu0.16.04.1_amd64.deb  Connection failed

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libe/libevent/libevent-core-2.0-5_2.0.21-stable-2ubuntu0.16.04.1_amd64.deb  Connection failed

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.7/mysql-server-5.7_5.7.23-0ubuntu0.16.04.1_amd64.deb  Connection failed

E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libh/libhtml-tagset-perl/libhtml-tagset-perl_3.20-2_all.deb  Connection failed

E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libu/liburi-perl/liburi-perl_1.71-1_all.deb  Connection failed

E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libh/libhtml-parser-perl/libhtml-parser-perl_3.72-1_amd64.deb  Connection failed

E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libc/libcgi-pm-perl/libcgi-pm-perl_4.26-1_all.deb  Connection failed

E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libf/libfcgi-perl/libfcgi-perl_0.77-1build1_amd64.deb  Connection failed

E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libc/libcgi-fast-perl/libcgi-fast-perl_2.10-1_all.deb  Connection failed

E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libe/libencode-locale-perl/libencode-locale-perl_1.05-1_all.deb  Connection failed

E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libh/libhtml-template-perl/libhtml-template-perl_2.95-2_all.deb  Connection failed

E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libt/libtimedate-perl/libtimedate-perl_2.3000-2_all.deb  Connection failed

E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libh/libhttp-date-perl/libhttp-date-perl_6.02-1_all.deb  Connection failed

E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libi/libio-html-perl/libio-html-perl_1.001-1_all.deb  Connection failed

E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libl/liblwp-mediatypes-perl/liblwp-mediatypes-perl_6.02-1_all.deb  Connection failed

E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libh/libhttp-message-perl/libhttp-message-perl_6.11-1_all.deb  Connection failed

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.7/mysql-client_5.7.23-0ubuntu0.16.04.1_all.deb  Connection failed

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by RiversC** [comment]
mysqladmin@mysqlhost:~$ wget http://azure.archive.ubuntu.com/ubuntu/pool/main/libh/libhttp-date-perl/libhttp-date-perl_6.02-1_all.deb
--2018-09-14 18:53:20--  http://azure.archive.ubuntu.com/ubuntu/pool/main/libh/libhttp-date-perl/libhttp-date-perl_6.02-1_all.deb
Resolving azure.archive.ubuntu.com (azure.archive.ubuntu.com)... 13.71.188.243
Connecting to azure.archive.ubuntu.com (azure.archive.ubuntu.com)|13.71.188.243|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10392 (10K) [application/x-debian-package]
Saving to: ‘libhttp-date-perl_6.02-1_all.deb’

libhttp-date-perl_6.02-1_all.deb                           100%[========================================================================================================================================>]  10.15K  --.-KB/s    in 0s

2018-09-14 18:53:21 (250 MB/s) - ‘libhttp-date-perl_6.02-1_all.deb’ saved [10392/10392]

**Comment by mattmcspirit** [comment]
Thanks Chris - let me investigate further on my systems.  It may be something on the Ubuntu side, but I'll have to spend some time looking into it and get back to you.

Thanks for your patience and have a good weekend!
Matt

**Comment by mattmcspirit** [comment]
Hey Chris - i tested both a manual VM, and the MySQL 5.7 on Ubuntu Linux 16.04 solution (you should have that in your gallery) and with both, the MySQL install worked fine. on the manual VM, there were no issues with the apt-get update, or the MySQL install, and from the gallery item, it worked fine also.  So, it *may* be something in your environment I'm afraid, but off the top of my head, I'm not quite sure what it would be.

**Comment by RiversC** [comment]
It could be but I am not sure what as I am able to manually download files and access the URLs from inside the test VM and the MySQLHost VM.  Unfortunately, I probably won't have much time this week to troubleshoot this further as I will be getting ready for Ignite.

**Comment by mattmcspirit** [comment]
Hi Chris,

So, if it works manually, my bash script (executed at the end of the VM deployment) would succeed without issue, so I'm not quite sure what's happening.

I'd suggest the following (if you get chance).  Clean up the Resource Groups that you've deployed for testing, including the azurestack-dbhosting RG.  You should then have no MySQL VMs left.  Once clean, i'd re-run the script.  If it passes, great, if it doesn't, I'd putty into the VM and install MySQL manually, ensuring you enable remote connections to the MySQL instance, and use the same password for MySQL as $secureVMpwd, for the root user. You could probably just manually step through my bash script to end up with the same end result.  Once MySQL is setup correctly, later in my script, it will add that MySQL host to the MySQL Resource Provider, so those values need to match.  To get past the "failed" step (again, assuming it fails), you'll need to edit your CSV file in your -downloadPath and change "Failed' to "Complete" and my script will carry on.

Hope that helps.

I'll be at Ignite also, so we could always troubleshoot there if you're able to access the system remotely.

Thanks!
Matt
