### ISSUE TITLE
New install stops. "No match was found for the specified search criteria and module names 'AzureRM.AzureStack Admin'..Exception.Message"

### ISSUE THREAD

**Issue by Laborman** [mattmcspirit/azurestack#44]
After a fresh install i recieve the following error:
VERBOSE: [11:31 AM]::[INSTALLPOWERSHELL]:: No match was found for the specified search criteria and module names 'AzureRM.AzureStack
Admin'..Exception.Message

PS C:\ConfigASDK> Uninstall-Module AzureRM.AzureStackAdmin -Force
PackageManagement\Uninstall-Package : No match was found for the specified search criteria and module names 
'AzureRM.AzureStackAdmin'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2157 char:21

I changed the lines to:

        Write-CustomVerbose -Message "Uninstalling previously existing Azure Stack modules"
        Uninstall-Module AzureRM.AzureStackAdmin -Force -ErrorAction SilentlyContinue
        Uninstall-Module AzureRM.AzureStackStorage -Force -ErrorAction SilentlyContinue
        Uninstall-Module -Name AzureStack -Force -ErrorAction SilentlyContinue

And now it will work.

**Comment by mattmcspirit** [comment]
Sorry about that - I copied and pasted from the updated official docs and forgot to add the -ErrorAction. It was there on my previous versions.  Should be fixed now.

Thanks!
