### ISSUE TITLE
MFA

### ISSUE THREAD

**Issue by zeronines** [mattmcspirit/azurestack#45]
About to start the script, I have MFA on my AAD account that I used.  Is the user password parameters required in Example 2?

**Comment by mattmcspirit** [comment]
I've not done any testing with MFA I'm afraid, so I'm not 100% sure what will happen.  The script logs in and out of both Azure and Azure Stack frequently to ensure tokens are fresh (due to some long running processes). Feel free to test and let me know. I haven't got bandwidth to test right now I'm afraid. For your second question, yes, and you can get the eval ISO by using the AzureStackDownloader.exe tool, or going via MSDN etc.  Thanks!

**Comment by mattmcspirit** [comment]
Also, just to set expectation, I don't expect it will work with MFA, so I'd plan to use an alternative account/sub if possible. Non-interactive PS-based MFA login, I don't believe, is possible.  Happy to be corrected though... Good luck!

**Comment by zeronines** [comment]
There was a test performed about 5 minutes in and I got the enclosed excerpt. I'm not sure if this is related to the MFA question.:


================

 VERBOSE: [5:23 PM]::[TEST LOGINS]:: ASDK Configurator will now test all logins

Name                                              : AzureStackAdmin
EnableAdfsAuthentication                          : False
OnPremise                                         : False
ActiveDirectoryServiceEndpointResourceId          : https://adminmanagement.zerodownstack.onmicrosoft.com/2039913c-c982-480e-b7be-a5c60514b6d3
AdTenant                                          : 
GalleryUrl                                        : https://adminportal.local.azurestack.external:30015/
ManagementPortalUrl                               : 
ServiceManagementUrl                              : 
PublishSettingsFileUrl                            : 
ResourceManagerUrl                                : https://adminmanagement.local.azurestack.external
SqlDatabaseDnsSuffix                              : 
StorageEndpointSuffix                             : local.azurestack.external
ActiveDirectoryAuthority                          : https://login.windows.net/
GraphUrl                                          : https://graph.windows.net/
GraphEndpointResourceId                           : https://graph.windows.net/
TrafficManagerDnsSuffix                           : 
AzureKeyVaultDnsSuffix                            : vault.local.azurestack.external
DataLakeEndpointResourceId                        : 
AzureDataLakeStoreFileSystemEndpointSuffix        : 
AzureDataLakeAnalyticsCatalogAndJobEndpointSuffix : 
AzureKeyVaultServiceEndpointResourceId            : https://vault.local.azurestack.external
AzureOperationalInsightsEndpointResourceId        : 
AzureOperationalInsightsEndpoint                  : 
VersionProfiles                                   : {}
ExtendedProperties                                : {}
BatchEndpointResourceId                           : 

VERBOSE: [5:23 PM]::[TEST LOGINS]:: Testing Azure login with Azure Active Directory

VERBOSE: [5:23 PM]::[TEST LOGINS]:: Value cannot be null.
Parameter name: Could not find tenant id for provided tenant domain 'zerodownstack.onmicrosoft.com'. Please ensure that the provided service principal is found 
in the provided tenant domain..Exception.Message



PS C:\ConfigASDK>

**Comment by mattmcspirit** [comment]
Could you provide the commands you used to run the script?  Please feel free to XXXXXXXXXXX your password and subscription ID info.  I just want to check how it's being called, but in reality, it's probably the MFA.  I haven't done any testing with MFA as i don't believe it can work.

If it is being blocked by MFA, I'm afraid you'll either have to install the pieces manually following the docs, or, do some editing of my script to prompt for manual login, take each section of my script in a PowerShell ISE and run them separately - each time it prompts you, enter your creds.  I don't know if that will work, but may be worth a try.

Or, just create a new Azure AD / Sub for test purposes and use that?

Thanks!
Matt

**Comment by zeronines** [comment]
.\ConfigASDK.ps1 -azureDirectoryTenantName "zerodownstack.onmicrosoft.com" -authenticationType AzureAD `

-downloadPath "D:\ASDKfiles" -ISOPath "E:\SW_DVD9_Win_Server_STD_CORE_2016_64Bit_English_-4_DC_STD_MLF_X21-70526.iso" -azureStackAdminPwd 'XXXXXXXXXXX' `

-VMpwd 'XXXXXXXXXXXXXXXXX' -azureAdUsername "keith@zeronines.com" -azureAdPwd 'XXXXXXXXXXXXXX' `

-registerASDK -useAzureCredsForRegistration -azureRegSubId "9c68ed65-33cb-4cfd-85d6-6c73f6c9798a"

**Comment by mattmcspirit** [comment]
Thanks - and to confirm, the keith@zeronines.com account is a Global Admin within the zerodownstack.onmicrosoft.com Azure Active Directory Tenant, and also, has Owner privileges on the subscription 9c68ed65-33cb-4cfd-85d6-6c73f6c9798a to create resources?

**Comment by zeronines** [comment]
Correct.

**Comment by mattmcspirit** [comment]
So this is what's being run at that point:

Login-AzureRmAccount -EnvironmentName "AzureCloud" -TenantId "$azureDirectoryTenantName" -Credential $asdkCreds -ErrorAction Stop
$testAzureSub = Get-AzureRmContext
Write-Output $testAzureSub

Rerun your initial command, but dot source it . .\ConfigASDK.ps1... etc then when it fails, it will retain the variables, so you can test the login manually using the above couple of lines and the error may present itself. If it fails, rerun but remove the -Credential $asdkCreds and see how it works when it prompts you for entry of creds.

**Comment by zeronines** [comment]
Matt,

 

I’ll bet you’re up to the top of your head at Ignite.

 

So, here’s what we did, we added a new global admin account (stackadmin@zerodownstack.onmicrosoft.com) to zerodownstack.onmicrosoft.com, new subscription with ownership, no MFA.

 

I think we’re getting the same error code.  Our ASDK box was configured based on the examples given from the installation guides, I’m not sure if we were to add other services?  Also, we used the Win Svr 2016 ISO image that we installed as the boot OS, downloaded from the Microsoft site.

 

Script to initiate the ConfigASDK.ps1 as follows (censored):

 

.\ConfigASDK.ps1 -azureDirectoryTenantName "contoso.onmicrosoft.com" -authenticationType AzureAD `

-downloadPath "D:\ASDKfiles" -ISOPath "D:\Windows_Server_2016_Datacenter_EVAL_en-us_14393_refresh.iso" -azureStackAdminPwd '################' `

-VMpwd '##############' -azureAdUsername "stackadmin@zerodownstack.onmicrosoft.com" -azureAdPwd '###############' `

-registerASDK -useAzureCredsForRegistration -azureRegSubId "99999999-9999-9999-9999-99999999999"

 

Any other ideas?

 

Thx.

 

Keith.

**Comment by zeronines** [comment]
Matt,

 

Unfortunately due to some conflicts I’m not at Ignite.

 

Here are the last few lines of the output in PowerShell – sorry for the colors:

 

VERBOSE: Catalog file 'Azs.Update.Admin.cat' is not found in the contents of the module 'Azs.Update.Admin' being installed.

VERBOSE: Installing the dependency module 'Azs.Update.Admin' with version '0.1.1' for the module 'AzureStack'.

VERBOSE: Module 'Azs.Update.Admin' was installed successfully to path 'C:\Program Files\WindowsPowerShell\Modules\Azs.Update.Admin\0.1.1'.

VERBOSE: Catalog file 'AzureStack.cat' is not found in the contents of the module 'AzureStack' being installed.

VERBOSE: Module 'AzureStack' was installed successfully to path 'C:\Program Files\WindowsPowerShell\Modules\AzureStack\1.4.0'.

VERBOSE: [5:28 AM]::[INSTALLPOWERSHELL]:: Updating ConfigASDKProgressLog.csv file with successful completion

 

 

Stage                      Status    

-----                      ------    

ExtractZip                 Skipped   

InstallPowerShell          Complete  

DownloadTools              Incomplete

HostConfiguration          Incomplete

Registration               Incomplete

UbuntuImage                Incomplete

WindowsImage               Incomplete

MySQLGalleryItem           Incomplete

SQLServerGalleryItem       Incomplete

VMExtensions               Incomplete

MySQLRP                    Incomplete

SQLServerRP                Incomplete

MySQLSKUQuota              Incomplete

SQLServerSKUQuota          Incomplete

UploadScripts              Incomplete

MySQLDBVM                  Incomplete

SQLServerDBVM              Incomplete

MySQLAddHosting            Incomplete

SQLServerAddHosting        Incomplete

AppServiceFileServer       Incomplete

AppServiceSQLServer        Incomplete

DownloadAppService         Incomplete

GenerateAppServiceCerts    Incomplete

CreateServicePrincipal     Incomplete

GrantAzureADAppPermissions Incomplete

InstallAppService          Incomplete

RegisterNewRPs             Incomplete

CreatePlansOffers          Incomplete

InstallHostApps            Incomplete

CreateOutput               Incomplete

 

 

Get-AzureRmContext : Run Login-AzureRmAccount to login.

At C:\ConfigASDK\ConfigASDK.ps1:987 char:1

+ Get-AzureRmContext -ListAvailable | Where-Object {$_.Environment -lik ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : AuthenticationError: (:) [Get-AzureRmContext], PSInvalidOperationException

    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.GetAzureRMContextCommand

 

 

PS D:\ASDKfiles>

**Comment by mattmcspirit** [comment]
Hi Keith,

Assuming you're still having issues, I think it's PS issues, so here's what i would do on the ASDK Host:

1. Close all PS windows
2. Open an ISE as administrator and run Get-AzureRMProfile
3. Assuming it returns results, do the following:

```powershell
Uninstall-AzureRmProfile -Profile '2017-03-09-profile' -Force
Uninstall-AzureRmProfile -Profile '2018-03-01-hybrid' -Force
Uninstall-AzureRmProfile -Profile latest -Force
Uninstall-Module -Name AzureRM.AzureStackAdmin -Force
Uninstall-Module -Name AzureRM.AzureStackStorage -Force
Uninstall-Module -Name AzureRM.Bootstrapper -Force
Uninstall-Module -Name AzureStack -Force
Get-Module -Name Azs.* -ListAvailable | Uninstall-Module -Force
```

You may get some errors saying modules were not found, but that's OK.

4. Go into the following folders and delete all the folders that start with Azure from the C:\Program Files\WindowsPowerShell\Modules and C:\Users\{yourusername}\Documents\WindowsPowerShell\Modules folders. Deleting these folders removes any existing PowerShell modules.  Make sure you include AzureRM.Bootstrapper for deletion.
5. Remove the PS Repository:

```powershell
Get-PSRepository | Unregister-PSRepository
```
6. Close the PS ISE and open a fresh one.
7. In Folder Explorer, navigate to your -downloadPath (ASDKfiles?) and delete the folders within it, and and .CSV, log files etc.
8. Delete your ConfigASDK.ps1 file from your C:\ConfigASDK folder.
9. Run the following:

```powershell
# Create directory on the root drive.
New-Item -ItemType Directory -Force -Path "C:\ConfigASDK"
Set-Location "C:\ConfigASDK"

# Download the ConfigASDK Script.
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Invoke-Webrequest http://bit.ly/configasdk -UseBasicParsing -OutFile ConfigASDK.ps1
```

10. Run your launch command again to run the script. Hopefully it should proceed as normal.

Let me know if that works and we can go from there.

Thanks,
Matt

**Comment by zeronines** [comment]
Matt,

 

Thanks, I’ll try that out and get back to you.  Is there any output that I should capture for you?

 

Thanks,

 

Keith.

**Comment by mattmcspirit** [comment]
Hi Keith,

Just let me know if there are any strange errors with the cleanup, and additionally, if there are any issues when you finally re-run the ConfigASDK.ps1 script. We can look into it then.

Thanks!
Matt

**Comment by zeronines** [comment]
Question as we’re going through the folder names:

 

We are only looking for folder that start with “Azure” verbatim.  Not anything that says AzureStack or AS…

 

Also, in the users section, we noticed that we’ve been using the AzureStackAdmin account for the scripts.  Is this okay or do we need to be logged in as Administrator?

 

Keith.

**Comment by mattmcspirit** [comment]
Hi Keith,

It'll be folders that start with AzureRM.modulename and Azs.modulename but these commands "should" catch most of them:

Uninstall-Module -Name AzureRM.AzureStackAdmin -Force
Uninstall-Module -Name AzureRM.AzureStackStorage -Force
Uninstall-Module -Name AzureRM.Bootstrapper -Force
Uninstall-Module -Name AzureStack -Force
Get-Module -Name Azs.* -ListAvailable | Uninstall-Module -Force

but just double check in the folders to make sure you get them all.

For user, yep, the azurestack\azurestackadmin is the right user.

Thanks!
Matt

**Comment by zeronines** [comment]
Matt,

 

It looks like I hit the same road block.  Are there any services or subscriptions in our subscription that we need to turn on?  The account is registered, and a subscription assigned to the Azure Admin account that we Authenticated to.  In the enclosed file is the powershell run output.  I blanked out our AAD password but left the local VM password.  I’m not sure if that’s an issue or not.

 

Keith.

**Comment by mattmcspirit** [comment]
Closing for now as I think you're unblocked. I will investigate MFA support for a future release.
