### ISSUE TITLE
Azure Stack 1809 / PS 1.5.0 / 2018-03-01-hybrid

### ISSUE THREAD

**Issue by eszych** [mattmcspirit/azurestack#48]
Even that you write your script will not work with it, I changed to PS Modules 1.5.0 and Profile 2018-03-01-hybrid by changing the lines:
950    Use-AzureRmProfile -Profile 2018-03-01-hybrid -Force -ErrorAction Stop
951    Install-Module -Name AzureStack -RequiredVersion 1.5.0 -Force -ErrorAction Stop

Ubuntu Image download failed - reason being that the registration could not be found, even if it was successfully registered. To fix that I changed line 1331:
1331  $Registration = ((Get-AzureRmResource | Where-Object { (($_.ResourceType -eq "Microsoft.AzureStack/registrations") -and ($_.Name -like "asdkreg-$asdkHostName*")) }) | Select-Object -First 1 -ErrorAction SilentlyContinue -Verbose).Name

Replace 
$asdkStorageAccount.PrimaryEndpoints.Blob.AbsoluteUri
with
$asdkStorageAccount.PrimaryEndpoints.Blob
Should replace at three occurences:
For Ubuntu Image:
$ubuntuServerURI = '{0}{1}/{2}' -f $asdkStorageAccount.PrimaryEndpoints.Blob.AbsoluteUri, $asdkImagesContainerName, $UbuntuServerVHD.Name
For Server Core Image: 
$serverCoreURI = '{0}{1}/{2}' -f $asdkStorageAccount.PrimaryEndpoints.Blob.AbsoluteUri, $asdkImagesContainerName, $serverCoreVHD.Name
For Server Full Image:
$serverFullURI = '{0}{1}/{2}' -f $asdkStorageAccount.PrimaryEndpoints.Blob.AbsoluteUri, $asdkImagesContainerName, $serverFullVHD.Name

**Comment by mattmcspirit** [comment]
This is all fixed in the next release - closing for now! Thanks!
