### ISSUE TITLE
Images Jobs failing

### ISSUE THREAD

**Issue by amalik99** [mattmcspirit/azurestack#56]
Various jobs are failing. 

****** Please wait until all jobs have completed/failed before re-running the main script ******
At least one of the jobs failed.
FAILED JOB: Job Name: AddUbuntuImage | Error Message: The resource type 'checkNameAvailability' could not be found in the namespace 'Microsoft.Storage' for api version '2017-10-01'. The suppo
rted api-versions are '2016-01-01,2015-06-15,2015-05-01-preview'.
FAILED JOB: Job Name: AddServerCoreImage | Error Message: The resource type 'checkNameAvailability' could not be found in the namespace 'Microsoft.Storage' for api version '2017-10-01'. The s
upported api-versions are '2016-01-01,2015-06-15,2015-05-01-preview'.
FAILED JOB: Job Name: AddServerFullImage | Error Message: The resource type 'checkNameAvailability' could not be found in the namespace 'Microsoft.Storage' for api version '2017-10-01'. The s
upported api-versions are '2016-01-01,2015-06-15,2015-05-01-preview'.
FAILED JOB: Job Name: AddMySQLAzpkg | Error Message: The resource type 'checkNameAvailability' could not be found in the namespace 'Microsoft.Storage' for api version '2017-10-01'. The suppor
ted api-versions are '2016-01-01,2015-06-15,2015-05-01-preview'.
FAILED JOB: Job Name: AddSQLServerAzpkg | Error Message: The resource type 'checkNameAvailability' could not be found in the namespace 'Microsoft.Storage' for api version '2017-10-01'. The su
pported api-versions are '2016-01-01,2015-06-15,2015-05-01-preview'.
FAILED JOB: Job Name: AddSQLServerRP | Error Message: The ServerCoreImage stage of the process has failed. This should fully complete before the Windows Server full image is created. Check th
e UbuntuServerImage log, ensure that step is completed first, and rerun.
FAILED JOB: Job Name: AddSQLServerSku | Error Message: The SQLServerRP stage of the process has failed. This should fully complete before the SKU and Quota are created. Check the SQLServerRP 
log, ensure that step is completed first, and rerun.
FAILED JOB: Job Name: DeploySQLServerHost | Error Message: The UbuntuServerImage stage of the process has failed. This should fully complete before the database VMs can be deployed. Check the
 UbuntuServerImage log, ensure that step is completed first, and rerun.
FAILED JOB: Job Name: AddSQLHosting | Error Message: The SQLServerSKUQuota stage of the process has failed. This should fully complete before the SQLServer database host has been deployed. Ch
eck the SQLServerSKUQuota log, ensure that step is completed first, and rerun.
FAILED JOB: Job Name: DeployAppServiceFS | Error Message: The ServerFullImage stage of the process has failed. This should fully complete before the File Server can be deployed. Check the Ser
verFullImage log, ensure that step is completed first, and rerun.
FAILED JOB: Job Name: DeployAppServiceDB | Error Message: The UbuntuServerImage stage of the process has failed. This should fully complete before the database VMs can be deployed. Check the 
UbuntuServerImage log, ensure that step is completed first, and rerun.
FAILED JOB: Job Name: DeployAppService | Error Message: The AppServiceFileServer stage of the process has failed. This should fully complete before the App Service deployment can be started. 
Check the AppServiceFileServer log, ensure that step is completed first, and rerun.
Please review the logs for further troubleshooting

**Comment by mattmcspirit** [comment]
The majority of jobs are failing here, by design. If the Ubuntu and Server Core/Full images fail to finish, all of the jobs that depend on them, gracefully fail too.  This is what has happened above. It seems that any situation that involves communication with a storage account, is failing. I haven't seen this in all of my **many** testing runs.

This message: 

```powershell
The resource type 'checkNameAvailability' could not be found in the namespace 'Microsoft.Storage' for api version '2017-10-01'. The supported api-versions are '2016-01-01,2015-06-15,2015-05-01-preview'.
```
Is one I haven't seen before. Can you confirm which ASDK build you are running in the Admin portal please?

I assume the prior steps, such as downloading Windows Updates, Registration etc, completed successfully?

Could you share details about your launch command? I.e. is this AAD or ADFS? DId you supply a ConfigAsdkFiles.zip etc?

Thanks,
Matt

**Comment by mattmcspirit** [comment]
Also, if you can share the logs with me, specifically the AddUbuntuImage, the AddSQLGalleryItem and the AddMySQLGalleryItem steps, from the Logs folder within your C:\ConfigASDK folder, that would be great, thanks.

**Comment by mattmcspirit** [comment]
Also, were any Azure/AzureStack PowerShell modules previously installed on this machine? Did the script try to clean them up, and then stop?  if it did, did you close all PS windows then restart from a new PS/ISE window?

This could be an issue with a newer/existing version of AzureRm.Storage on your system.

**Comment by mattmcspirit** [comment]
Could you please run the following, when you get a chance:

```powershell
Get-Module Azure* -ListAvailable
```

Thanks!
Matt

**Comment by mattmcspirit** [comment]
Let me know how you're doing so I can get you unblocked!  thanks!

**Comment by amalik99** [comment]
It was probably various PowerShell versions, i did a clean build and it worked well.

**Comment by mattmcspirit** [comment]
Thanks for the update!
