### ISSUE TITLE
Can't retry appservice deployment due to an existing database

### ISSUE THREAD

**Issue by gijs007** [mattmcspirit/azurestack#59]
My previous run of the post deployment script failed, during the step  DeployAppService  (probably during the deployment of an Appservice virtual machine, see ticket #60 ).
If I rerun the post deployment script it fails, due to a database (appservice_hosting) which already exists.

The AppServiceLog for this run shows:

```
[7BE0:2078][2018-11-16T07:52:55]: [Websites]: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The database 'appservice_hosting' already exists. Please choose another SQL instance or remove the existing database and retry.

   at Microsoft.Web.Hosting.Common.DatabaseServerHelper.TestConnectivity(String serverName, String userName, String password, String dbObjsPrefix)
```
Perhaps it's possible to adjust the script so that:
1. it checks if the database exists and validates it.
2. Reuse the existing database if it's valid and continue from there.

Alternatively it might be an idea to remove the existing database, as cleanup step for this task within the script. (This would be necessary if the database ends up being corrupted anyhow)

**Comment by mattmcspirit** [comment]
The creation of the DB and associated logins is automatically handled by the AppService.exe automated installer (which my script simply calls) and its this that cant handle the existing DB unfortunately. I can write a check to see if the DB exists, along with its logins, then clean it up if it does exist (as it will likely be a rerun).

As far as I know, there’s no way to reuse the existing DB at install time unless it’s handled by the AppService.exe itself.

Probably easier just to clean up.

Leave it with me.

**Comment by gijs007** [comment]
So far it's working nicely, Appservice deployment is running for 17 minutes now. Instead of the almost instant failure after the rerun.
Goodwork 👍 

If the AppService database is removed at 90%, I assume Appservice will simply reinstall from scratch?
It will take a little longer, but as long as it doesn't fail that's nothing to worry about IMO. Although obviously it would be nicer if everything is completed in the fastest possible way.

Maybe it's an idea to utilize PowerShell Desired State Configuration? (For the more complex steps which take a while)
If setup correctly it can start over from where it failed, instead of redoing everything.

**Comment by gijs007** [comment]
After running the updated script the deployment still failed. I've send you the log by email.
At least it doesn't fail because of the database. :)

**Comment by mattmcspirit** [comment]
Let's close this one out, as we know that the script now handles cleaning up the DB, so let's focus on the other issue with re-running a failed App Service deployment.
