### ISSUE TITLE
Appservice failed to deploy : Shared worker tier timed out

### ISSUE THREAD

**Issue by vniklas** [mattmcspirit/azurestack#69]
"code": "ProvisioningState/failed/VmProvisioningTimeout",
      "level": "Error",
      "displayStatus": "Provisioning failed",
      "message": "VM 'SharedWorkerTierScaleSet_0' failed to provision with timeout.",
      "time": "2018-12-21T13:32:57.9619623+00:00"
    }

**Comment by mattmcspirit** [comment]
What are the specs of your hardware? Ram, CPU and number of HDDs/Size and capacity.

Also, share your launch command when you ran the script.

Thanks!

**Comment by mattmcspirit** [comment]
Also, please email your AppService log to asdkconfigurator @ outlook .com

Thanks!

**Comment by mattmcspirit** [comment]
Closing - fixed by using slightly larger VM sizes
