### ISSUE TITLE
Error while running the script

### ISSUE THREAD

**Issue by rathishrms** [mattmcspirit/azurestack#76]
I get the below error, any help is much appreciated.

C:\ConfigASDK\ConfigASDK.ps1 : The term '.\Scripts\GetJobStatus.ps1' is not 
recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At line:1 char:1
+ .\ConfigASDK.ps1 -azureDirectoryTenantName "rathishr85hotmail.onmicro ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Scripts\GetJobStatus.ps1:Stri 
   ng) [ConfigASDK.ps1], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,ConfigASDK.ps1

**Comment by mattmcspirit** [comment]
What do you see in your C:\ConfigASDK\Scripts folder? Can you list the files in there?

Have you tried re-running the script?

Was this a clean system?

Can you provide more of your launch command?

Please email me your zipped log files to asdkconfigurator @ outlook .com and I’ll try to take a look sometime this week.

**Comment by rathishrms** [comment]
> What do you see in your C:\ConfigASDK\Scripts folder? Can you list the files in there?
>  There is no scripts folder present.
> Have you tried re-running the script?
> 
> Was this a clean system?
> Yes
> Can you provide more of your launch command?
>  
> Please email me your zipped log files to asdkconfigurator @ outlook .com and I’ll try to take a look sometime this week.

**Comment by rathishrms** [comment]
i think it was the change in location. Manually copied the scripts folder and now its running. Thanks Matt, appreciate the assistance.
