### ISSUE TITLE
Feature request: Support for "custom domain" on the install

### ISSUE THREAD

**Issue by BjornAnd** [mattmcspirit/azurestack#81]
**Describe the issue**
We have quite a few ASDK installs, and have configured the installations so that we have different external FQDNs on the installs. 
The ASDK configurator didn't really like that. :)
So the feature request is to get support for using an alternative External DomainFQDN.

**So this is how I made it work**
Ok. First; this is my quick and dirty fix to just get it to work... :)
It should be a loop and stuff, but its just a test. Also "borrrowed" some of the functions from the ConfigASDK.ps1 just to try it out...

[MockupUpdateSetupFiles.ps1.txt](https://github.com/mattmcspirit/azurestack/files/2922126/MockupUpdateSetupFiles.ps1.txt)

**How it might be done**
I havn't made any changes in the ASDK configurator install. But a suggestion would be to add a optional parameter (eg: "-ExternalDomainFQDN") and if this is specified when running ASDK configurator then it would use this new ExternalDomainFQDN instead of "azurestack.local" :)

**Comment by mattmcspirit** [comment]
Hey Bjorn, you should check out Branch 1901.1...

https://github.com/mattmcspirit/azurestack/tree/1901.1?files=1

Another contributor kindly added the same functionality and while I haven’t tested it yet, I’m sure it would work fine.

I haven’t finished fixing everything for 1901.1 yet, so you may want to wait until I release it fully next week, after some more testing.

Enjoy!
