### ISSUE TITLE
Missing link to download Windows2016 image

### ISSUE THREAD

**Issue by jjindrich** [mattmcspirit/azurestack#84]
Please add link to download Win2016 server
https://software-download.microsoft.com/download/pr/Windows_Server_2016_Datacenter_EVAL_en-us_14393_refresh.ISO

**Comment by mattmcspirit** [comment]
Hi - the official way to download the ISO is via the Evaluation portal, https://www.microsoft.com/en-us/evalcenter/, so from a Microsoft perspective (and being a Microsoft employee), I'll continue to point people down that path. However, people will be able to use your link above if they look at this thread :)

Thanks,
Matt
