### ISSUE TITLE
DeployAppService job is failing

### ISSUE THREAD

**Issue by akn9050** [mattmcspirit/azurestack#88]
**Describe the issue**
Hi Matt, DeployAppService job is failing. I tried to re-run the script but every time getting the same error.
I have attached logs file. Can you please look into this issue. I have sent logs file to asdkconfigurator @ outlook .com

**Comment by mattmcspirit** [comment]
Thanks - what was the issue?

**Comment by akn9050** [comment]
App service extension was not working. I had to delete the appservice-infra RG and start the script again.
