### ISSUE TITLE
 AddMySQLAzpkg job is failing

### ISSUE THREAD

**Issue by akn9050** [mattmcspirit/azurestack#97]
Hi Matt,

AddMySQLAzpkg job is failing everytime with rerun.

![image](https://user-images.githubusercontent.com/27498287/61587185-c20a0900-aba2-11e9-9ae4-f930ce397191.png)

I have sent log file in mail.

**Comment by mattmcspirit** [comment]
Hi,

Do you definitely have the latest version of the ConfigASDK?  Can you email the version you are using, to me, or attach here? From lines 2375 to 2396, you should have this:

```powershell
    # Define the DB Gallery Item jobs
    $jobName = "AddMySQL57Azpkg"
    $AddMySQL57Azpkg = {
        Start-Job -Name AddMySQL57Azpkg -InitializationScript $export_functions -ArgumentList $ASDKpath, $customDomainSuffix, $deploymentMode, $tenantID, $asdkCreds, $ScriptLocation, `
            $branch, $sqlServerInstance, $databaseName, $tableName -ScriptBlock {
            Set-Location $Using:ScriptLocation; .\Scripts\AddGalleryItems.ps1 -ASDKpath $Using:ASDKpath -customDomainSuffix $Using:customDomainSuffix `
                -deploymentMode $Using:deploymentMode -tenantID $Using:TenantID -asdkCreds $Using:asdkCreds -ScriptLocation $Using:ScriptLocation -branch $Using:branch `
                -azpkg "MySQL57" -sqlServerInstance $Using:sqlServerInstance -databaseName $Using:databaseName -tableName $Using:tableName
        } -Verbose -ErrorAction Stop
    }
    JobLauncher -jobName $jobName -jobToExecute $AddMySQL57Azpkg -Verbose

    $jobName = "AddMySQL80Azpkg"
    $AddMySQL80Azpkg = {
        Start-Job -Name AddMySQL80Azpkg -InitializationScript $export_functions -ArgumentList $ASDKpath, $customDomainSuffix, $deploymentMode, $tenantID, $asdkCreds, $ScriptLocation, `
            $branch, $sqlServerInstance, $databaseName, $tableName -ScriptBlock {
            Set-Location $Using:ScriptLocation; .\Scripts\AddGalleryItems.ps1 -ASDKpath $Using:ASDKpath -customDomainSuffix $Using:customDomainSuffix `
                -deploymentMode $Using:deploymentMode -tenantID $Using:TenantID -asdkCreds $Using:asdkCreds -ScriptLocation $Using:ScriptLocation -branch $Using:branch `
                -azpkg "MySQL80" -sqlServerInstance $Using:sqlServerInstance -databaseName $Using:databaseName -tableName $Using:tableName
        } -Verbose -ErrorAction Stop
    }
    JobLauncher -jobName $jobName -jobToExecute $AddMySQL80Azpkg -Verbose
```

Notice the -azpkg in each of those examples.  I suspect you may have an old file, which only has -azpkg "MySQL" instead of the 2 new options.

Let me know.

Thanks,
Matt

**Comment by akn9050** [comment]
Hi Matt,

Yeah, you are right. I checked the script it was an older script. Which has only -azpkg "MySQL" instead of the 2 new options. Thanks for the Help. 
I have one more question. If I am using ASDK 1905.04 and running your script for configuring ASDK. Will it work with older version (1905.04) or any other version of ASDL or will it work with latest ASDK only.

Thanks,
Amit

**Comment by mattmcspirit** [comment]
Hey,

It should be fine with 1905 - i didn't make any changes to PowerShell module use between 1905 and 1906, I mainly focused on adding a few new features and better error checking so you should be fine.

The challenge you have now though, is if you download the new ConfigASDK.ps1 file and run over the top of the old one, the ConfigASDK progress database (the one that displays incomplete, complete, failed etc) won't line up, as the 1906 version has extra items in it:

            MySQL57GalleryItem   = "Incomplete";
            MySQL80GalleryItem   = "Incomplete";
            SQLServerGalleryItem = "Incomplete";

So it may be tricky to deploy over the top, unless you edit the LocalDB database manually and adjust those rows.

If you can redeploy the ASDK, that may be the easier option.

Hope that helps,
Matt

**Comment by akn9050** [comment]
Hi Matt,

Got it. I tried to run the script on top of old and it failed. 
Thanks a lot for your help ans support.

Amit
